name       : kcoreaddons
version    : 5.71.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kcoreaddons-5.71.0.tar.xz : e95008b032e299cf47f596739d9236701e2f55e507734f33b8ea497882fd130b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
