name       : kcoreaddons
version    : 5.79.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kcoreaddons-5.79.0.tar.xz : 6f221bd93be73aeec863cd7089c69e84fef76bea83a906c6cd2c853937813659
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - shared-mime-info
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
