name       : kcoreaddons
version    : 5.49.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kcoreaddons-5.49.0.tar.xz : 12afb12f79505614f6d5624d6c39b90b5fc39e4b1b5ddb2203622bbeb6144203
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
