name       : kcoreaddons
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kcoreaddons-5.25.0.tar.xz : 5479180bcb6034cfcfbe779d88d91e11233f2120ba6314d180a1f87ad3f02c09
license    :
    - BSD-3-Clause
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
