name       : kcoreaddons
version    : 5.52.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kcoreaddons-5.52.0.tar.xz : 49aaae09f4196f2aef7b78ea2ee4d290bbedd9fe3831680197e3a767697c78d3
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
