name       : kcoreaddons
version    : 5.94.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kcoreaddons-5.94.0.tar.xz : 5c10b6ce070d6aa9b15abe7483b67f8802cec175e0eaeefc18a27c0e01ce110b
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - shared-mime-info
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
