name       : kcoreaddons
version    : 5.74.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kcoreaddons-5.74.0.tar.xz : e122d0750c594dc68dea20e40c833b6615f5ddf21a2b2e439c7236e73f4523a8
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
