name       : kcoreaddons
version    : 5.50.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kcoreaddons-5.50.0.tar.xz : 48f4fc35bc7c8d556610f828082c84771a100a19c36f1d6c42130a31ac22f5ac
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
