name       : kcoreaddons
version    : 5.106.0
release    : 73
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kcoreaddons-5.106.0.tar.xz : e80c50d0d9fc402726d92c869b0314dbb8fe8a2163627f695e0897d7c27cc07c
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - shared-mime-info
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
