name       : kcoreaddons
version    : 5.67.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kcoreaddons-5.67.0.tar.xz : 95fd37ac2e42ca2a00bd9d67955af57a78e9f1cde69acd1af79cdedb3ec994e3
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
