name       : kcoreaddons
version    : 5.68.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kcoreaddons-5.68.0.tar.xz : c578ae30b4161e45e672d613d2d9c5575a849d21909d9817f90a441044df65d7
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
