name       : kcoreaddons
version    : 5.35.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.35/kcoreaddons-5.35.0.tar.xz : dc4c499bd0ac0a42f44651ce4526dbd1485ab0ef5452d891da8e93da3c08210b
license    :
    - BSD-3-Clause
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
