name       : kcoreaddons
version    : 5.54.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kcoreaddons-5.54.0.tar.xz : e9e8d033b912345d2b5eca7d1cddc4e3b3ce758539f6378fb248222d0d3a47d8
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
