name       : kcoreaddons
version    : 5.56.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kcoreaddons-5.56.0.tar.xz : 9f41039f1bd453087ff784e9e95d4f09624ff893fe0298d3c986a6a554b37b9e
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
