name       : kcoreaddons
version    : 5.39.0
release    : 10
source     :
    - https://download.kde.org/stable/frameworks/5.39/kcoreaddons-5.39.0.tar.xz : 9f6e76c2a15252d2974271e4e3734a64aec157a434251c23b27efaa809d95363
license    :
    - BSD-3-Clause
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
