name       : kcoreaddons
version    : 5.59.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kcoreaddons-5.59.0.tar.xz : 9df3668696b2e722196ce93fff86bae8ea343c13c008bf2ad6f8d3cff15b5aca
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
