name       : kcoreaddons
version    : 5.40.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kcoreaddons-5.40.0.tar.xz : 25109dd486891c113f8b01d55f4c02e35b65b456c3879eb7da5045e595db8f58
license    :
    - BSD-3-Clause
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
