name       : kcoreaddons
version    : 5.76.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kcoreaddons-5.76.0.tar.xz : fbab3e3e18f42922ecdc50138ed31f62007cafa902b959d89b1233b5557282d6
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
