name       : kcoreaddons
version    : 5.63.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kcoreaddons-5.63.0.tar.xz : 4d6e76e2a191b7a4c5f46b4cf8ed14edee25eb4357a82b1dc8f4753d1d47c5f0
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
