name       : kcoreaddons
version    : 5.72.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kcoreaddons-5.72.0.tar.xz : b404433ae2310b91475598e801a8cecc048d9cfd85f664e02feb7a166f877bb9
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
