name       : kcoreaddons
version    : 5.53.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kcoreaddons-5.53.0.tar.xz : fd64d27412c212840a3d8f7000d5f6c1616787e2e3419170872726574acb026b
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
