name       : kcoreaddons
version    : 5.105.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kcoreaddons-5.105.0.tar.xz : 915cd3ac5bb3963fe79a643d70f109a9aa198f97e6a2b5c72f09cd955238daa2
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - shared-mime-info
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
