name       : kcoreaddons
version    : 5.70.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/kcoreaddons-5.70.0.tar.xz : fa86760b2074ccadab0417220fee1253d731ab7f2f4d7a2857ba463ab4ff4781
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
