name       : kcoreaddons
version    : 5.65.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kcoreaddons-5.65.0.tar.xz : 0f334b123b307829d11a39f639845f2f74d290490b264d9b188f1a785e16bf41
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
