name       : kcoreaddons
version    : 5.55.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kcoreaddons-5.55.0.tar.xz : 3cd840b3f308b4529012d16aeee05494b5e55c938b6ad7f6580d4d055d61ebc8
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
