name       : kcoreaddons
version    : 5.36.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.36/kcoreaddons-5.36.0.tar.xz : 9d4b26bf22d1326c37f33aa4727942325cad2b23e5b3f1e32ec9ee558e9b5594
license    :
    - BSD-3-Clause
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
