name       : kcoreaddons
version    : 5.62.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kcoreaddons-5.62.0.tar.xz : 3819e2792a2e61444e337cd1a4cbdc362c18810918376eefc30b203fbd160b41
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
