name       : kcoreaddons
version    : 5.57.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kcoreaddons-5.57.0.tar.xz : 7c2573de9b745e55fe61cff26941839cff0d2e40b6c5d791c24c9d6cc8cf7485
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
